# To use the examples, copy the html, swf, and svg files to your web server directory.


svgviewer.swf: SVGViewer.as svgviewer.mxml *.as data/*.as nodes/*.as utils/*.as events/*.as
	mxmlc -compiler.source-path ../../../ -- svgviewer.mxml

clean:
	rm svgviewer.swf

